module.exports = {
  projects: [
    '<rootDir>/apps/tin',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api-interfaces',
    '<rootDir>/libs/auth/domain',
    '<rootDir>/libs/auth/feature-login',
    '<rootDir>/libs/auth/shell',
    '<rootDir>/libs/shared/ui',
    '<rootDir>/libs/debt/domain',
    '<rootDir>/libs/debt/feature-list',
    '<rootDir>/libs/debt/shell',
    '<rootDir>/libs/debt/feature-add-debt',
    '<rootDir>/libs/debt/feature-preview',
    '<rootDir>/libs/debt/feature-edit',
    '<rootDir>/libs/film-database/domain',
    '<rootDir>/libs/film-database/feature-film-list',
    '<rootDir>/libs/film-database/feature-film-preview',
    '<rootDir>/libs/film-database/feature-film-add',
    '<rootDir>/libs/film-database/feature-film-edit',
    '<rootDir>/libs/film-database/shell',
    '<rootDir>/libs/film-database/ui-components',
    '<rootDir>/libs/film-database/feature-actor-list',
  ],
};
